# -*- mode: ruby -*-
# vi: set ft=ruby :

def env_or_default(env_name, default)
  env_value = ENV.fetch(env_name, "")
  return env_value.empty? ? default : env_value
end

ruby_version = env_or_default("RUBY_VERSION", "3.3.8")
redmine_version = env_or_default("REDMINE_VERSION", "6.0.6")
redmine_path = env_or_default("REDMINE_PATH", "/opt/redmine")

n_cpus = ENV.fetch("VAGRANT_CPUS") {
  require "etc"
  [1, Etc.nprocessors / 2].max
}
memory_mega_bytes = ENV.fetch("VAGRANT_MEMORY", 1024 * 8).to_i

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.provider(:virtualbox) do |vb|
    vb.cpus = n_cpus
    vb.memory = memory_mega_bytes
  end

  # If we clone private repository, enable following.
  #config.ssh.forward_agent = true
  config.vm.network(:forwarded_port, guest: 3000, host: 4000)

  config.vm.provision(:shell, privileged: false, inline: <<~SHELL)
    set -eux -o pipefail

    export RUBY_VERSION=#{ruby_version}
    export REDMINE_VERSION=#{redmine_version}
    export REDMINE_PATH=#{redmine_path}

    export DEBIAN_FRONTEND=noninteractive

    exec run-parts --verbose --exit-on-error /vagrant/provision_scripts
  SHELL
end
