#!/bin/sh

set -eux

# https://aquaproj.github.io/docs/install/#download-prebuilt-binaries-from-github-releases
# https://aquaproj.github.io/docs/tutorial/
# https://zenn.dev/shunsuke_suzuki/books/aqua-handbook/viewer/tutorial

sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  curl

# https://aquaproj.github.io/docs/products/aqua-installer#shell-script
curl -sSfL https://raw.githubusercontent.com/aquaproj/aqua-installer/v3.1.1/aqua-installer |
  bash

echo 'export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH"' >> ~/.bashrc
