#!/bin/bash

ruby_version=3.3.6

eval "$(~/.local/bin/mise activate bash --shims)"

set -eux -o pipefail

# https://github.com/rbenv/ruby-build/wiki#ubuntudebianmint
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  autoconf \
  patch \
  build-essential \
  rustc \
  libssl-dev \
  libyaml-dev \
  libreadline6-dev \
  zlib1g-dev \
  libgmp-dev \
  libncurses5-dev \
  libffi-dev \
  libgdbm6 \
  libgdbm-dev \
  libdb-dev \
  uuid-dev

mise install ruby@$ruby_version
