services:
  ollama:
    # https://hub.docker.com/r/ollama/ollama/tags
    image: ollama/ollama:0.11.4
    restart: always
    volumes:
      - ollama:/root/.ollama
    ports:
      - "127.0.0.1:11434:11434"

volumes:
  ollama:
