#!/bin/bash

# https://github.com/nvm-sh/nvm/tree/v0.40.3?tab=readme-ov-file#installing-and-updating

set -eux -o pipefail

sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  curl

curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

echo 'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"' >> ~/.bashrc
echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm' >> ~/.bashrc
